version: 2.1
jobs:
    build:
        working_directory: ~/runs
        docker:
            - image: cimg/openjdk:21.0.6
        steps:
            - checkout
            - run: mvn install
            - run: java -jar driver-app/target/blizzard-sdk-driver-app-1.0-SNAPSHOT.jar

    sonar:
        docker:
            - image: cimg/openjdk:21.0.6
        steps:
            - checkout
            - run:
                  name: SonarCloud Analysis
                  command: mvn install sonar:sonar
workflows:
    main:
        jobs:
            - build
            - sonar:
                context: SonarCloud
