version: 2
jobs:
    build:
        working_directory: ~/runs
        docker:
            - image: circleci/openjdk:8-jdk-stretch
        steps:
            - checkout
            - run: mvn install
            - run: java -jar driver-app/target/blizzard-sdk-driver-app-1.0-SNAPSHOT.jar
