blizz-api-config:
  baseUrl: https://eu.battle.net
  oauth2:
    client:
      grant_type: client_credentials
      clientId: ${BLIZZARD_API_CLIENT_ID} # Obtained when registering a new
      # application on Blizzard API Portal
      clientSecret: ${BLIZZARD_API_CLIENT_SECRET} # Obtained when registering a new
      # application on Blizzard API Portal
      accessTokenUri: ${blizz-api-config.baseUrl}/oauth/token
